# Generated by Django 3.1.3 on 2020-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201113_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='mobile-2468068_1920.jpg', upload_to=''),
        ),
    ]
