# Generated by Django 3.1.3 on 2020-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201122_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='phone-2245651_1280.png', help_text='minimum 235x460 px please.', upload_to=''),
        ),
    ]
